# You should make sure all lines marked with XXX match your setup.

substitutions:
  # Unique device ID in HA
  deviceid: "lglivingroom" # XXX
  # Unique device name in HA (sensor names will be prefixed by this name)
  devicename: "LG Living Room" # XXX
  # The input temperature sensor in HA.
  temperature_sensor_entity_id: sensor.my_sensor # XXX
  # Over heating installer setting 15.
  # Determines at which temperature the unit starts/stops heating.
  #   0 = default behavior for unit
  #   1 = +4C/+6C
  #   2 = +2C/+4C
  #   3 = -1C/+1C
  #   4 = -0.5C/+0.5C
  over_heating_installer_setting: "0" # XXX

# Encryption key for HA. See https://esphome.io/components/api.html.
api:
  encryption:
    key: my_key # XXX

wifi:
  ssid: "wifi-SSID" # XXX
  password: "wifi-password" # XXX

  manual_ip:
    static_ip: 192.168.1.200 # XXX
    gateway: 192.168.1.1 # XXX
    subnet: 255.255.255.0 # XXX

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${deviceid} Fallback Hotspot"
    password: "hotspot-password" # XXX

captive_portal:

ota:
  password: ""

logger:
  level: DEBUG

<<: !include base.yaml
