# You should make sure all lines marked with XXX match your setup.

substitutions:
  # Unique device ID in HA
  deviceid: "lglivingroom" # XXX
  # Unique device name in HA (sensor names will be prefixed by this name)
  devicename: "LG Living Room" # XXX
  # The input temperature sensor in HA.
  temperature_sensor_entity_id: sensor.my_sensor # XXX
  # Set to "true" if the temperature sensor and Home Assistant use Fahrenheit instead of Celsius.
  fahrenheit: "false" # XXX
  # If multiple controllers are connected to a single indoor unit, only one of them should be
  # configured as "master controller". Slave mode is a new and experimental feature for this
  # ESPHome controller and might not work well.
  # If you're connecting a single controller, this should be set to "false".
  is_slave_controller: "false"

# Encryption key for HA. See https://esphome.io/components/api.html.
api:
  encryption:
    key: my_key # XXX

wifi:
  ssid: "wifi-SSID" # XXX
  password: "wifi-password" # XXX

  manual_ip:
    static_ip: 192.168.1.200 # XXX
    gateway: 192.168.1.1 # XXX
    subnet: 255.255.255.0 # XXX

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${deviceid} Fallback Hotspot"
    password: "hotspot-password" # XXX

captive_portal:

ota:
  platform: esphome
  password: ""

logger:
  level: DEBUG

<<: !include base.yaml
